New rule add
atomspace/eslint-plugin-naming-convention pull request #45
Opened 2019-11-05 18:53 UTC by Artefall

Resolves #4

2019-11-06 10:06 UTC, constgen requested changes

2019-11-06 10:06 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	}
Add a case with importing from long paths
```js
import noop from '../../services/noop.js'
```

2019-11-06 10:06 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	}
Add a case with importing without an extension
```js
import noop from '../../services/noop.js'
```

2019-11-06 10:06 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	]
Add a case with importing from long paths

2019-11-06 10:06 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	]
Add a case with importing without an extension

2019-11-06 10:06 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +const errorMessage = `import file does not match with variable name`;
**to match ~~with~~ something**

2019-11-06 18:38 UTC, Artefall commented on test/import-file-and-var-name-matching.test.js
> +	}
Why should I need to ignore expression, when file name starts with numbers?

2019-12-03 22:19 UTC, constgen requested changes
1. Add necessary test cases
2. Avoid hardcoded suffixes and determine them dinamically by this pattern `*.[suffix].{ext}`

2019-12-03 22:19 UTC, constgen commented on src/rules/import-file-and-var-name-matching/index.js
> +	let fileNameWIhoutExtension = path.parse(string).name;
`WIhout`

2019-12-03 22:19 UTC, constgen commented on src/rules/import-file-and-var-name-matching/index.js
> +						message: `import file does not match variable name`
We should ask user to fix the variable name and not the filename. Extra feature if we suggest what names are compatible with the given filename.

2019-12-03 22:19 UTC, constgen commented on src/rules/import-file-and-var-name-matching/index.js
> +						message: `import file does not match variable name`
We should ask user to fix the variable name and not the filename. Extra feature if we suggest what names are compatible with the given filename.

2019-12-03 22:19 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	}
We have no solution for this. We are open for ideas

2019-12-03 22:19 UTC, constgen commented on test/import-file-and-var-name-matching.test.js
> +	],
We need a case for importing without a declaration. They should be ignored
```js
import './css/styles.css`
```

2019-12-03 22:19 UTC, constgen commented on src/rules/import-file-and-var-name-matching/index.js
> +	let fileName = path.parse(pathToFile).name;
Duplicated code

2019-12-04 17:19 UTC, constgen requested changes
Not all comments are fixed

2019-12-10 07:29 UTC, constgen requested changes
Not all comments are fixed

2019-12-12 08:32 UTC, constgen approved these changes

2019-12-17 17:40 UTC, merged