Add 'No native classes names in identifiers names' rule
atomspace/eslint-plugin-naming-convention pull request #51
Opened 2019-11-26 22:07 UTC by PyTechMike

Resolve #28

2019-11-27 09:02 UTC, constgen requested changes

2019-11-27 09:02 UTC, constgen commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
Add case `let numbers = [1,2,3]`

2019-11-27 09:02 UTC, constgen commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
Add a case for an empty code

2019-11-27 21:37 UTC, PyTechMike commented on src/rules/no-native-classes-names-in-identifiers-names.js
> +			noNativeClassesNamesInIdentifiersNames: 'Avoid using native classes names in identifiers names.'
Is this variant better? `Avoid using native classes names in identifiers (such as "Object" or "String")`

2019-11-27 21:47 UTC, PyTechMike commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
> Add cases for reading identifiers with classes names. Such cases should not fail. Existing cases make no sense

What do you mean when you talk about "reading identifiers with classes names"? Can you add some examples? And why existing ones are senseless?

2019-11-27 21:57 UTC, PyTechMike commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
> Add case `let numbers = [1,2,3]`

Is it going to fail or no?

2019-11-27 22:39 UTC, PyTechMike commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
Is native class name could be only in the end of the identifier on in the middle/start also?

2019-11-28 14:50 UTC, constgen commented on test/no-native-classes-names-in-identifiers-names.test.js
> +		}
All this conversation is related to `valid` cases. Identifiers that doesn't contain classes names are not helpful. You may leave only one to be sure that you don't invalidate everything.

2019-11-28 14:52 UTC, constgen commented on src/rules/no-native-classes-names-in-identifiers-names.js
> +			noNativeClassesNamesInIdentifiersNames: 'Avoid using native classes names in identifiers names.'
It is better. And can be used. But think what if you show what words exactly were used

2019-11-28 14:53 UTC, constgen commented on src/rules/no-native-classes-names-in-identifiers-names.js
> +module.exports = {
`no-native-names`

2019-11-28 14:55 UTC, constgen commented on src/rules/no-native-classes-names-in-identifiers-names.js
> +				if (nativeClassNameInIdentifier) {
`isNativeClassNameInIdentifier` sounds like a function name

2019-11-28 14:56 UTC, constgen requested changes
Conversations updated

2019-11-28 15:00 UTC, PyTechMike commented on src/rules/no-native-classes-names-in-identifiers-names.js
> +				if (nativeClassNameInIdentifier) {
> `isNativeClassNameInIdentifier` sounds like a function name

As I know, `is` prefix is compatible both for functions and booleans and the best way to name them

2019-11-28 17:28 UTC, PyTechMike commented
Improve cases validation with natives in the end of identifiers

2019-12-02 08:49 UTC, constgen requested changes
Some comments are not resolved

2019-12-03 20:41 UTC, PyTechMike commented
@constgen please check out my comment 
https://github.com/atomspace/eslint-plugin-naming-convention/issues/28#issuecomment-561339815

2019-12-03 22:32 UTC, constgen submitted a review, later dismissed

2019-12-10 07:25 UTC, constgen approved these changes

2019-12-10 21:44 UTC, merged